### ISSUE TITLE
define-it doesn't translate the source text to the target language.

### ISSUE THREAD

**Issue by hongyi-zhao** [jcs-elpa/define-it#3]
On Ubuntu 20.04, I'm using define-it with the following configuration:

```emacs-lisp
(use-package google-translate
  :custom
  (google-translate-backend-method 'curl)
  :config
  (setq ; Auto detect language.
        google-translate-default-source-language "auto" 
        ; Set your target language.
        google-translate-default-target-language "cn")
  (defun google-translate--search-tkk () "Search TKK." (list 430675 2721866130)))  

(use-package define-it
  :config
  (setq ; Output with buffer.
        define-it-output-choice 'view 
        ; Output with tooltip.
        ;define-it-output-choice 'pop
        ))

```
After I've selected/high-lightened some words, I run the `M-x define-it-at-point` command, but just find that define-it doesn't translate the source text to the target language, as shown below:

![image](https://user-images.githubusercontent.com/11155854/126949651-35dd0100-04fd-46ff-82c6-ee3045ff8253.png)

Any hints for this problem?

Regards,
HY

**Comment by jcs090218** [comment]
Hmm... I cannot reproduce this. My configuration does not seems much different than yours. Here is my config, 

```el

(use-package google-translate
  :init
  (setq google-translate-default-source-language "auto"
        google-translate-default-target-language "zh-TW")
  :config
  (defun jcs--google-translate--search-tkk ()
    "Search TKK."
    (list 430675 2721866130))
  (advice-add 'google-translate--search-tkk :override #'jcs--google-translate--search-tkk))


(use-package define-it
  :init
  (setq define-it-output-choice 'view))
```

but I have the output correctly, see below

```
DEFINE

has an expansion in a fixed (x-indenpendent) basis

DICTIONARY

No definition found

TRANSLATION

具有固定（x 獨立）基礎的擴展

WIKIPEDIA SUMMARY

No article found
```

**Comment by hongyi-zhao** [comment]
Got it. Thank you for showing me your complete configuration. The problematic configuration is the following line:

> ```emacs-lisp
> google-translate-default-target-language "cn")
> ```

In my case, the above line should read like this:

```emacs-lisp
 ; It seems that the language name is case-insentitive, all forms like "zh-cn", "zh-CN", and "ZH-CN" are vaild.
 ; See the following websites for the possiable languages list.
 ; https://py-googletrans.readthedocs.io/en/latest/#googletrans-languages
 ; https://developers.google.com/admin-sdk/directory/v1/languages
 google-translate-default-target-language "zh-CN")
```

This way, I will get the correct output, as shown below:

![image](https://user-images.githubusercontent.com/11155854/126955364-0dc1c335-a9bc-4c8f-9df1-3f9cb064662f.png)
