### ISSUE TITLE
Add option to set default translation languages

### ISSUE THREAD

**Issue by port19x** [jcs-elpa/define-it#9]
This would improve my user experience by reducing necessary interactions from 3 to 1.
Suggested variable names:
- `define-it-translate-default-from`
- `define-it-translate-default-to`

**Comment by jcs090218** [comment]
Yeah, I agree. Feel free to open PRs for this! :)

**Comment by port19x** [comment]
Just figured out my desired UX improvement can also be accomplished by disabling translation via the `define-it-show-google-translate` variable
